# NUMPY

## 1- Numpy Array

### Numpy arrayleri python listelerine benziyor ama onlarin aksine, farkli veri tiplerinde elemalar iceremez. Tek veri tipi elemanlari olmasi gerekiyor.

In [5]:
import numpy as np # gerekli kutuphaneyi importlama

In [15]:
# Listelerden array yaratmak
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [16]:
type(x)

numpy.ndarray

In [17]:
y = np.array(["a","b","c"])
y

array(['a', 'b', 'c'], dtype='<U1')

In [18]:
type(y)

numpy.ndarray

In [19]:
z = np.array([1,2,3,4,"5"]) # string casting
z

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [20]:
k = np.array([1,2,3,4.5]) # float casting
k

array([1. , 2. , 3. , 4.5])

In [21]:
m = np.array([1,2,3,4.5,"7.8"]) # string casting
z
m

array(['1', '2', '3', '4.5', '7.8'], dtype='<U32')

## 2 - Array Manual Type
### Array'in elemanlarinin tipinin ne olacagini ozellikle belirtebiliriz

In [26]:
x = np.array([1,2,3,4.6], dtype="int32") # data tipini ozellikle belirtirsek casting yapmaz (yuvarlama islemi yapmaz)
x

array([1, 2, 3, 4])

In [27]:
x = np.array(["5"], dtype="int32") # str elamani int yaptik
x

array([5])

## 3 - Zero Array

In [31]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros([3,4]) # 3 row ve 4 column olan bir array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros([3,3,5], dtype= int) 

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [38]:
np.zeros([1,2], dtype= str)

array([['', '']], dtype='<U1')

In [39]:
np.zeros([4,2,3], dtype= bool)

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

In [40]:
np.zeros([3,8,8,5])

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



## 4 - Specific Element Array

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.full(4,4)

array([4, 4, 4, 4])

In [ ]:
np.full([5,5],"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [ ]:
np.full([4,5], 6.7, dtype= str)

array([['6', '6', '6', '6', '6'],
       ['6', '6', '6', '6', '6'],
       ['6', '6', '6', '6', '6'],
       ['6', '6', '6', '6', '6']], dtype='<U1')

## 5 - Consequtive Numbers Array

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(12,0,-2)

array([12, 10,  8,  6,  4,  2])

## 6 - Dividing Interval

In [50]:
np.linspace(1,2) # default olarak 50 nokta dondurur

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [52]:
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

In [53]:
np.linspace(1,2, 3)

array([1. , 1.5, 2. ])

In [54]:
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## 7 - Normal Distribution Array

In [55]:
np.random.normal(0,1,[4,5]) # medyan: 0, standart sapma:1, array

array([[ 0.38596182, -0.21790094,  0.90990558,  0.60882368,  2.20266525],
       [-0.11772711,  1.27423492, -0.60396585,  0.06654369, -1.87348833],
       [-0.19429414, -0.59244984, -2.54966428,  1.67763718,  0.72915596],
       [-1.29166556,  1.23965171,  0.62461739, -0.45193983,  1.24209425]])

In [57]:
np.random.normal(0,100,[4,5])

array([[ 193.73486201,  -61.25007231,   42.91700284,  236.64586268,
          27.90974272],
       [ -58.51862639,   58.92570546,  -15.52243559,    6.9424722 ,
         -64.8024587 ],
       [-251.82021577,   94.15313315,  123.75621352,  -30.63528631,
          85.47845794],
       [  63.69624867,  -26.8600382 ,  -88.01602938,   84.89445991,
         -61.87604439]])

In [59]:
np.random.normal(200,100,[4,5])


array([[169.20518266,  63.34884256, 233.04011342, 148.07379047,
        428.58330732],
       [144.07269075, 318.11879604, 139.83958994, 140.14464083,
        166.44578551],
       [224.19761393, 139.0995215 ,   6.59128492, 124.87955852,
         74.25967499],
       [326.43573364,  86.53522714, 394.45828071, 154.1199603 ,
        192.98448358]])

## 8 - Random Integer Array

## 9 - Identity Matrix

array([[5, 6, 6, 6],
       [1, 1, 8, 8],
       [6, 1, 3, 6]])