# NUMPY

In [2]:
import numpy as np # gerekli kutuphaneyi importlama

## 1- Numpy Array

Numpy arrayleri python listelerine benziyor ama onlarin aksine, farkli veri tiplerinde elemalar iceremez. Tek veri tipi elemanlari olmasi gerekiyor.

In [15]:
# Listelerden array yaratmak
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [16]:
type(x)

numpy.ndarray

In [17]:
y = np.array(["a","b","c"])
y

array(['a', 'b', 'c'], dtype='<U1')

In [18]:
type(y)

numpy.ndarray

In [19]:
z = np.array([1,2,3,4,"5"]) # string casting
z

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [20]:
k = np.array([1,2,3,4.5]) # float casting
k

array([1. , 2. , 3. , 4.5])

In [21]:
m = np.array([1,2,3,4.5,"7.8"]) # string casting
z
m

array(['1', '2', '3', '4.5', '7.8'], dtype='<U32')

## 2 - Array Manual Type
Array'in elemanlarinin tipinin ne olacagini ozellikle belirtebiliriz

In [26]:
x = np.array([1,2,3,4.6], dtype="int32") # data tipini ozellikle belirtirsek casting yapmaz (yuvarlama islemi yapmaz)
x

array([1, 2, 3, 4])

In [27]:
x = np.array(["5"], dtype="int32") # str elamani int yaptik
x

array([5])

## 3 - Zero Array

In [31]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros([3,4]) # 3 row ve 4 column olan bir array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros([3,3,5], dtype= int) 

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [38]:
np.zeros([1,2], dtype= str)

array([['', '']], dtype='<U1')

In [39]:
np.zeros([4,2,3], dtype= bool)

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

In [40]:
np.zeros([3,8,8,5])

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



## 4 - Specific Element Array

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.full(4,4)

array([4, 4, 4, 4])

In [ ]:
np.full([5,5],"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [ ]:
np.full([4,5], 6.7, dtype= str)

array([['6', '6', '6', '6', '6'],
       ['6', '6', '6', '6', '6'],
       ['6', '6', '6', '6', '6'],
       ['6', '6', '6', '6', '6']], dtype='<U1')

## 5 - Consequtive Numbers Array

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(12,0,-2)

array([12, 10,  8,  6,  4,  2])

## 6 - Dividing Interval

In [50]:
np.linspace(1,2) # default olarak 50 nokta dondurur

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [52]:
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

In [53]:
np.linspace(1,2, 3)

array([1. , 1.5, 2. ])

In [54]:
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## 7 - Normal Distribution Array

In [55]:
np.random.normal(0,1,[4,5]) # medyan: 0, standart sapma:1, array

array([[ 0.38596182, -0.21790094,  0.90990558,  0.60882368,  2.20266525],
       [-0.11772711,  1.27423492, -0.60396585,  0.06654369, -1.87348833],
       [-0.19429414, -0.59244984, -2.54966428,  1.67763718,  0.72915596],
       [-1.29166556,  1.23965171,  0.62461739, -0.45193983,  1.24209425]])

In [57]:
np.random.normal(0,100,[4,5])

array([[ 193.73486201,  -61.25007231,   42.91700284,  236.64586268,
          27.90974272],
       [ -58.51862639,   58.92570546,  -15.52243559,    6.9424722 ,
         -64.8024587 ],
       [-251.82021577,   94.15313315,  123.75621352,  -30.63528631,
          85.47845794],
       [  63.69624867,  -26.8600382 ,  -88.01602938,   84.89445991,
         -61.87604439]])

In [59]:
np.random.normal(200,100,[4,5])


array([[169.20518266,  63.34884256, 233.04011342, 148.07379047,
        428.58330732],
       [144.07269075, 318.11879604, 139.83958994, 140.14464083,
        166.44578551],
       [224.19761393, 139.0995215 ,   6.59128492, 124.87955852,
         74.25967499],
       [326.43573364,  86.53522714, 394.45828071, 154.1199603 ,
        192.98448358]])

## 8 - Random Integer Array

In [60]:
np.random.randint(1,10,[3,4])

array([[5, 6, 6, 6],
       [1, 1, 8, 8],
       [6, 1, 3, 6]])

In [61]:
np.random.randint(1,10,[3,3,4])


array([[[7, 5, 8, 6],
        [8, 4, 3, 7],
        [2, 2, 3, 5]],

       [[7, 8, 6, 6],
        [6, 1, 8, 7],
        [4, 6, 5, 2]],

       [[7, 9, 3, 7],
        [9, 5, 7, 9],
        [7, 7, 5, 3]]])

## 9 - Identity Matrix

In [ ]:
np.eye(4,4) # birim matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 10 - Array Operations

In [ ]:
x = np.array([1,2,3])
y = np.array([2,4,8])
print(x*y) # ayni row'a denk gelenler carpilir
x+y

[ 2  8 24]


array([ 3,  6, 11])

In [ ]:
x * 3


array([3, 6, 9])

In [ ]:
x = x * 3
x

array([3, 6, 9])

## 11 - Array Attribute

In [30]:
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
y = np.zeros([2,5,4])
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [48]:
print(x.shape) # sekli
print(y.shape)

(2, 3)
(2, 5, 4)


In [44]:
print(x.ndim) # boyut
print(y.ndim)

2
3


In [45]:
print(x.size) # eleman sayisi
print(y.size)

6
40


In [46]:
print(x.dtype)
print(y.dtype)

float64
float64


## 12 - Reshaping

In [51]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
a.ndim

1

In [54]:
a.size

10

In [56]:
a.reshape(2,5) 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [67]:
print(a.ndim)
a.reshape(2,5).ndim

1


2

In [64]:
a.reshape(6,2) # eleman sayisi tutmasi lazim

ValueError: cannot reshape array of size 10 into shape (6,2)

In [68]:
a.reshape(-1,2) # burada -1'i kendisi kac vermesi gerektigini buluyor x * 2 = 10 ... x=5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [70]:
# yeni bir boyut eklemek
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [74]:
a[np.newaxis, :].shape

(1, 10)

In [77]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [79]:
a[:, np.newaxis].shape

(10, 1)

In [82]:
print(a[:, None])
print(a[None, :])# None'de ayni islemi yapiyor

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


## 13 - Concatenation 

In [85]:
x = np.array([1,2,3])
y = np.array([2,4,8])
np.concatenate([x,y])

array([1, 2, 3, 2, 4, 8])

In [87]:
l = [10,11] # list ile birlesir
np.concatenate([x,y,l])

array([ 1,  2,  3,  2,  4,  8, 10, 11])

In [89]:
l = (10,11,12) # tuple ile birlesir
np.concatenate([x,y,l])

array([ 1,  2,  3,  2,  4,  8, 10, 11, 12])

In [91]:
l = [34,35,22.4]
np.concatenate([x,y,l]) # listede birisi float ise hepsini float yapar


array([ 1. ,  2. ,  3. ,  2. ,  4. ,  8. , 34. , 35. , 22.4])

In [92]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [94]:
x = np.array([[1,2,3],
              [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
print(x.shape)
print(a.shape)

(2, 3)
(4,)


In [99]:
np.concatenate([x,y]) # column ve row uyusmazligi var

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [104]:
np.concatenate([x,x]) # altalta birlestirdi defoult olarak

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [106]:
np.concatenate([x,x], axis = 1) # yanyana birlestirdi


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## 14 - Stack

In [108]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [109]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
np.stack([a,b],axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## 15 - Split

In [111]:
l = [10,20,30,40,50,60,70,80]

In [113]:
# [0,1], [2,3,4,5], [6,7]
np.split(l , [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [116]:
a = np.array([10,20,30,40,50,60,70,80])
np.split(a , [3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [120]:
# split sonucunu farkli deherlere atiyabiliriz
x,y,z = np.split(a , [3,5])
print(x)
print(y)
z

[10 20 30]
[40 50]


array([60, 70, 80])

In [122]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [124]:
np.vsplit(a, [1]) # vertical split

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [125]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [128]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [129]:
np.hsplit(a, [2])[0]

array([[ 0,  1],
       [10, 11]])

In [131]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [136]:
np.hsplit(a, [2,5])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4],
        [12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [138]:
a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [139]:
np.vsplit(a, [2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

## 16 - Sorting

In [140]:
a = np.array([20,32,5,52,63])
a

array([20, 32,  5, 52, 63])

In [141]:
np.sort(a)

array([ 5, 20, 32, 52, 63])

In [142]:
a

array([20, 32,  5, 52, 63])

In [143]:
a = np.array([3,1,6,4,8,2])

In [144]:
idxs = np.argsort(a) # siralanmis listenin indexini bize verir
idxs

array([1, 5, 0, 3, 2, 4], dtype=int64)

## 17 - Indexing

In [3]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a[0]

array([1, 2, 3, 4, 5])

In [5]:
a[1]

array([ 6,  7,  8,  9, 10])

In [7]:
a[1][0]

6

In [8]:
a[0].ndim

1

In [12]:
a[0][2] = 31
a[0].reshape(5,1)

array([[ 1],
       [ 2],
       [31],
       [ 4],
       [ 5]])

In [13]:
a

array([[ 1,  2, 31,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
a[1][1] = 20.41 # array veri tipi belliyse sonradan gelen veri o tipe uygun convert edilir
a

array([[ 1,  2, 31,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[1][1] = '31'
a

array([[ 1,  2, 31,  4,  5],
       [ 6, 31,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
# slice indexing
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
a[1]

array([ 6,  7,  8,  9, 10])

In [22]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[:2]

array([1, 2, 3, 4, 5])

In [28]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [30]:
a[2,3]

14

In [32]:
a[:,3] # butun rowlari al ama sadece index 3teki column u al

array([ 4,  9, 14, 19])

In [33]:
a[0, 2:4]

array([3, 4])

In [34]:
a[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

## 18 - Fancy Indexing
belirli indexleri cekmek

In [36]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
idxs = [4,5,7,9,13]
idxs

[4, 5, 7, 9, 13]

In [38]:
a[idxs]

array([ 5,  6,  8, 10, 14])

In [39]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
print(a[0:2,1])
print(a[0:2,1].shape)

[[1]
 [5]]
(2,)


In [43]:
print(a[0:2,1:3])
print(a[0:2,1:3].shape)

[[1 2]
 [5 6]]
(2, 2)


In [44]:
a[0,[1,3]]

array([1, 3])

In [45]:
a[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [47]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
idx1 = [1,3,2]
idx2 = [3,0,2]

In [49]:
a[idx1,idx2]

array([ 9, 16, 13])

In [53]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
x[[1,2,3]] = 333
x

array([  1, 333, 333, 333,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [55]:
x[[3,5,7]] = 222,444,555
x

array([  1, 333, 333, 222,   5, 444,   7, 555,   9,  10,  11,  12,  13,
        14])

In [56]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a[1,[1,3]].ndim

1

## 19 - Subarray

In [60]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [61]:
b = a[:2,:3]
b

array([[1, 2, 3],
       [6, 7, 8]])

In [62]:
b[0,0] = 100
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [63]:
a # b'de yaptigimiz degisilik a array'i uzerinde de etkili oldu

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [64]:
c = a[:2,:3].copy()
c

array([[100,   2,   3],
       [  6,   7,   8]])

In [66]:
c[0,1] = 222
c

array([[100, 222,   3],
       [  6,   7,   8]])

In [67]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

## 20 - Conditional Indexing
guclu tool - filtrelemeye yarar

In [68]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [70]:
a[a<5]

array([1, 2, 3, 4])

In [71]:
filt = a < 3
a[filt]

array([1, 2])

In [72]:
b = np.array([2,3,3,4,5,61,7,8,11])
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [73]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [74]:
filt2= a==b
a[filt2]

array([3, 4, 5, 7, 8])

In [75]:
b[filt2]

array([3, 4, 5, 7, 8])

In [76]:
# broadcasting
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [77]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [78]:
filt3 = (a < 3) | (a > 5)
a[filt3]

array([1, 2, 6, 7, 8, 9])

In [80]:
a[(a > 3) & (a <= 5)]

array([4, 5])

In [3]:
# filtrenin degili
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
filt4 = a < 5
filt4

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [5]:
a[filt4]

array([1, 2, 3, 4])

In [11]:
filt5 = (a>5) & (a<9)
a[!(filt5)]

SyntaxError: invalid syntax (Temp/ipykernel_6968/3655795700.py, line 2)

In [16]:
~(filt5)

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
a[~(filt5)]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## 21 - Sum

In [18]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
np.sum(a)

210

In [20]:
filt = a < 5
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [21]:
np.sum(a[filt])

10

In [22]:
filt = (a > 3) & (a < 10)
a[filt]

array([4, 5, 6, 7, 8, 9])

In [23]:
np.sum(a[filt])

39

In [24]:
# belirli axis uzerine islem
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))


[34 38 42 46 50]
[15 40 65 90]


## 22 - All - Any

In [25]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [27]:
np.all(a>-1)

True

In [28]:
np.all(a>5)

False

In [29]:
filt = a > -1
np.all(filt)

True

In [30]:
np.all(a > 5, axis=1)

array([False, False,  True,  True])

In [31]:
np.all(a > 5, axis=0)


array([False, False, False, False, False])

In [32]:
a > 17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [33]:
np.any(a>17)

True